name: Build and Run

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  build-run:
    name: Build and run with startup msg verification
    uses: arielswalker/ds/.github/workflows/build-run-app-reusable.yml@test-jphickey-fix-998-workflow-config
    with:
      startup-string: Application initialized
